# Caso Práctico: Neurona de McCulloch y Pitts

## 1.- Implementación de la neurona MP

In [1]:
import numpy as np

### Declaración de la clase MPNeuron


In [6]:
class MPNeuron:
    def __init__(self):
        self.threshold = None

    def model( self, x ):
        #input [ x1, x2, x3, ..., xn ] [ 1, 1, 0, ..., 1 ]
        z = sum( x )
        return ( z >= self.threshold )
    
    def predict( self, x ):
        #input [ [ 1, 1, 0, ..., 1 ], [ 1, 1, 0, ..., 1 ] ]
        y = []

        for val in x:
            result = self.model( val )
            y.append( result )
        
        return np.array( y )
    


### Instanciando la clase


In [9]:
mpNeuron = MPNeuron()

In [15]:
mpNeuron.threshold = 3

In [16]:
mpNeuron.predict( [ [ 1, 1, 0, 0 ], [ 1, 1, 0, 1 ], [ 1, 0, 0, 0 ] ] )

array([False,  True, False])

### Implementando compuerta lógica AND

In [18]:
mpNeuron.threshold = 2
mpNeuron.predict( [ [ 0, 0 ], [ 1, 0 ], [ 0, 1 ] , [ 1, 1 ] ] )

array([False, False, False,  True])

### Implementando compuerta lógica OR


In [22]:
mpNeuron.threshold = 1
#mpNeuron.predict( [ [ 0, 0 ], [ 1, 0 ], [ 0, 1 ] , [ 1, 1 ] ] )
mpNeuron.predict( [ [ 0, 0, 1, 1 ], [ 0, 0, 0, 1 ] ] )

array([ True,  True])

In [23]:
mpNeuron.threshold = 1
#mpNeuron.predict( [ [ 0, 0 ], [ 1, 0 ], [ 0, 1 ] , [ 1, 1 ] ] )
mpNeuron.predict( [ [ 0, 0, 1, 1 ], [ 0, 0, 0, 1 ] ] )

array([ True,  True])